import os

M8FLOW_TO_SPIFF = {
    # ------------------------
    # Core environment / logging
    # ------------------------
    "M8FLOW_BACKEND_ENV": "SPIFFWORKFLOW_BACKEND_ENV",
    "M8FLOW_BACKEND_LOG_LEVEL": "SPIFFWORKFLOW_BACKEND_LOG_LEVEL",
    "M8FLOW_BACKEND_DATABASE_TYPE": "SPIFFWORKFLOW_BACKEND_DATABASE_TYPE",
    "M8FLOW_BACKEND_DATABASE_URI": "SPIFFWORKFLOW_BACKEND_DATABASE_URI",
    "M8FLOW_BACKEND_UPGRADE_DB": "M8FLOW_BACKEND_UPGRADE_DB",

    # ------------------------
    # Network / URLs / ports
    # ------------------------
    "M8FLOW_BACKEND_PORT": "M8FLOW_BACKEND_PORT",
    "M8FLOW_BACKEND_URL": "SPIFFWORKFLOW_BACKEND_URL",
    "M8FLOW_BACKEND_URL_FOR_FRONTEND": "SPIFFWORKFLOW_BACKEND_URL_FOR_FRONTEND",
    "M8FLOW_BACKEND_URL_FRONTEND": "SPIFFWORKFLOW_BACKEND_URL_FRONTEND",
    "M8FLOW_BACKEND_CORS_ALLOW_ORIGINS": "SPIFFWORKFLOW_BACKEND_CORS_ALLOW_ORIGINS",

    # ------------------------
    # BPMN / process models
    # ------------------------
    "M8FLOW_BACKEND_BPMN_SPEC_ABSOLUTE_DIR": "SPIFFWORKFLOW_BACKEND_BPMN_SPEC_ABSOLUTE_DIR",

    # ------------------------
    # Auth / OIDC / Keycloak
    # ------------------------
    "M8FLOW_BACKEND_OPEN_ID_SERVER_URL": "SPIFFWORKFLOW_BACKEND_OPEN_ID_SERVER_URL",
    "M8FLOW_BACKEND_OPEN_ID_CLIENT_ID": "SPIFFWORKFLOW_BACKEND_OPEN_ID_CLIENT_ID",
    "M8FLOW_BACKEND_OPEN_ID_CLIENT_SECRET_KEY": "SPIFFWORKFLOW_BACKEND_OPEN_ID_CLIENT_SECRET_KEY",
    "M8FLOW_BACKEND_OPEN_ID_IS_AUTHORITY_FOR_USER_GROUPS": "SPIFFWORKFLOW_BACKEND_OPEN_ID_IS_AUTHORITY_FOR_USER_GROUPS",

    # ------------------------
    # Celery / Redis
    # ------------------------
    "M8FLOW_BACKEND_CELERY_ENABLED": "SPIFFWORKFLOW_BACKEND_CELERY_ENABLED",
    "M8FLOW_BACKEND_CELERY_BROKER_URL": "SPIFFWORKFLOW_BACKEND_CELERY_BROKER_URL",
    "M8FLOW_BACKEND_CELERY_RESULT_BACKEND": "SPIFFWORKFLOW_BACKEND_CELERY_RESULT_BACKEND",
    "M8FLOW_BACKEND_RUNNING_IN_CELERY_WORKER": "SPIFFWORKFLOW_BACKEND_RUNNING_IN_CELERY_WORKER",

    # ------------------------
    # Optional / Compose
    # ------------------------
    "M8FLOW_BACKEND_APPLICATION_ROOT": "SPIFFWORKFLOW_BACKEND_APPLICATION_ROOT",
    "M8FLOW_BACKEND_LOAD_FIXTURE_DATA": "SPIFFWORKFLOW_BACKEND_LOAD_FIXTURE_DATA",
    "M8FLOW_BACKEND_RUN_BACKGROUND_SCHEDULER_IN_CREATE_APP": "SPIFFWORKFLOW_BACKEND_RUN_BACKGROUND_SCHEDULER_IN_CREATE_APP",
    "M8FLOW_BACKEND_AUTHENTICATION_DISABLED": "SPIFFWORKFLOW_BACKEND_AUTHENTICATION_DISABLED",
    "M8FLOW_BACKEND_LOCAL_BPMN_SPEC_DIR": "SPIFFWORKFLOW_BACKEND_LOCAL_BPMN_SPEC_DIR",

    # ------------------------
    # Connector proxy
    # ------------------------
    "M8FLOW_BACKEND_CONNECTOR_PROXY_URL": "SPIFFWORKFLOW_BACKEND_CONNECTOR_PROXY_URL",

    # ------------------------
    # Encryption
    # -------------------------
    "M8FLOW_BACKEND_ENCRYPTION_LIB": "SPIFFWORKFLOW_BACKEND_ENCRYPTION_LIB",
    "M8FLOW_BACKEND_ENCRYPTION_KEY": "SPIFFWORKFLOW_BACKEND_ENCRYPTION_KEY",

    # ------------------------
    # Permissions
    # ------------------------
    "M8FLOW_BACKEND_PERMISSIONS_FILE_NAME": "SPIFFWORKFLOW_BACKEND_PERMISSIONS_FILE_NAME",
    "M8FLOW_BACKEND_PERMISSIONS_FILE_ABSOLUTE_PATH": "SPIFFWORKFLOW_BACKEND_PERMISSIONS_FILE_ABSOLUTE_PATH",
}


def apply_m8flow_env_mapping() -> None:
    for m8_key, spiff_key in M8FLOW_TO_SPIFF.items():
        value = os.getenv(m8_key)
        if value is not None:
            os.environ[spiff_key] = value
