# Redirect stub — logic lives in m8flow_core.auth.adapters.keycloak
from m8flow_core.auth.adapters.keycloak import *  # noqa: F401, F403
from m8flow_core.auth.adapters.keycloak import (  # noqa: F401
    SPOKE_CLIENT_ID_PLACEHOLDER,
    BACKEND_REDIRECT_PLACEHOLDER,
    FRONTEND_REDIRECT_PLACEHOLDER,
    DEFAULT_ROLES_PREFIX,
    REALM_URL_PREFIX,
    ADMIN_CONSOLE_URL_PREFIX,
    BACKEND_URL_PLACEHOLDER,
    FRONTEND_URL_PLACEHOLDER,
    FRONTEND_CLIENT_ID,
    POST_LOGOUT_REDIRECT_URIS_ATTR,
    GLOBAL_ONLY_REALM_ROLE_NAMES,
    GLOBAL_ONLY_USERNAMES,
    get_master_admin_token,
    realm_exists,
    tenant_login_authorization_url,
    ensure_backend_redirect_uri_in_keycloak_client,
    load_realm_template,
    create_realm_from_template,
    tenant_login,
    create_user_in_realm,
    delete_realm,
    update_realm,
    verify_admin_token,
)
