"""add_template_table

Revision ID: 22aaaa61d8f6
Revises: 2cfce680c743
Create Date: 2026-01-15 11:56:30.471226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22aaaa61d8f6'
down_revision = '2cfce680c743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "m8flow_templates",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("template_key", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("m8f_tenant_id", sa.String(length=255), sa.ForeignKey("m8flow_tenant.id"), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("bpmn_object_key", sa.String(length=1024), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True)),
        sa.Column("modified_by", sa.String(length=255), nullable=False),
        sa.UniqueConstraint("m8f_tenant_id", "template_key", "version", name="uq_template_key_version_tenant"),
    )
    op.create_index('ix_template_is_published', 'm8flow_templates', ['is_published'], unique=False)
    op.create_index('ix_template_m8f_tenant_id', 'm8flow_templates', ['m8f_tenant_id'], unique=False)
    op.create_index('ix_template_status', 'm8flow_templates', ['status'], unique=False)
    op.create_index('ix_template_template_key', 'm8flow_templates', ['template_key'], unique=False)
    op.create_index('ix_template_visibility', 'm8flow_templates', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_template_visibility', table_name='m8flow_templates')
    op.drop_index('ix_template_template_key', table_name='m8flow_templates')
    op.drop_index('ix_template_status', table_name='m8flow_templates')
    op.drop_index('ix_template_m8f_tenant_id', table_name='m8flow_templates')
    op.drop_index('ix_template_is_published', table_name='m8flow_templates')
    op.drop_table('m8flow_templates')
    # ### end Alembic commands ###