"""Add m8flow_nats_tokens table

Revision ID: b8837274af96
Revises: f6a7b8c9d0e1
Create Date: 2026-03-12 13:07:44.681299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8837274af96'
down_revision = 'f6a7b8c9d0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m8flow_nats_tokens',
    sa.Column('m8f_tenant_id', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('created_at_in_seconds', sa.Integer(), nullable=False),
    sa.Column('updated_at_in_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['m8f_tenant_id'], ['m8flow_tenant.id'], ),
    sa.PrimaryKeyConstraint('m8f_tenant_id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m8flow_nats_tokens')
    # ### end Alembic commands ###
