apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://m8flow-loki:3100
    isDefault: false
    jsonData:
      maxLines: 1000

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://m8flow-tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://m8flow-prometheus:9090
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: Prometheus cluster
    uid: prometheus-cluster
    type: prometheus
    access: proxy
    url: http://m8flow-prometheus:9090
    isDefault: false

  - name: M8Flow Postgres
    uid: postgres-m8flow
    type: postgres
    access: proxy
    url: m8flow-db:5432
    user: $POSTGRES_USER
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1500
    secureJsonData:
      password: $POSTGRES_PASSWORD
