"""Optional capability protocols for the auth seam.

Callers must not sniff these with ``hasattr``. Use the typed accessors on
``AuthProvider`` (``directory_admin`` / ``provisioning``), which return the
capability or raise ``CapabilityNotSupported``.
"""
from __future__ import annotations

from typing import Protocol

from m8flow_backend.integrations.auth.base.models import Group, Membership, Tenant, TenantRef, User


class SupportsDirectoryAdmin(Protocol):
    """Mutating directory operations. Not every provider implements these."""

    def create_user(
        self,
        *,
        username: str,
        authentication_identifier: str,
        email: str | None = None,
        password: str | None = None,
    ) -> User: ...

    def delete_user(self, *, username: str, authentication_identifier: str) -> None: ...

    def add_member(self, *, username: str, tenant_ref: TenantRef) -> Membership: ...

    def remove_member(self, *, username: str, tenant_ref: TenantRef) -> None: ...

    def get_member(self, *, username: str, tenant_ref: TenantRef) -> User: ...

    def list_members(
        self,
        *,
        tenant_ref: TenantRef,
        query: str = "",
        limit: int = 50,
    ) -> list[User]: ...

    def assign_roles(self, *, username: str, tenant_ref: TenantRef, roles: list[str]) -> Membership: ...

    def get_tenant(self, tenant_ref: TenantRef) -> Tenant: ...

    def create_tenant(self, *, alias: str, name: str | None = None) -> Tenant: ...

    def update_tenant(self, tenant_ref: TenantRef, *, name: str) -> Tenant: ...

    def delete_tenant(self, tenant_ref: TenantRef) -> None: ...

    def list_groups(self, tenant_ref: TenantRef) -> list[Group]: ...

    def create_group(self, tenant_ref: TenantRef, *, identifier: str) -> Group: ...

    def delete_group(self, group: Group) -> None: ...

    def rename_group(self, group: Group, *, identifier: str, roles: list[str] | None = None) -> Group: ...

    def add_group_member(self, group: Group, *, username: str) -> None: ...

    def remove_group_member(self, group: Group, *, username: str) -> None: ...

    def list_group_members(self, group: Group) -> list[User]: ...

    def set_group_roles(self, group: Group, *, roles: list[str]) -> Group: ...

    def roles_for_group(self, group: Group) -> list[str]: ...

    def ensure_default_groups(self, tenant_ref: TenantRef) -> list[Group]: ...


class SupportsProvisioning(Protocol):
    """Tenant-realm and client provisioning. Keycloak-heavy; optional on the seam."""

    def create_tenant_realm(self, tenant_ref: TenantRef, *, display_name: str | None = None) -> Tenant: ...

    def delete_tenant_realm(self, tenant_ref: TenantRef) -> None: ...

    def update_tenant_realm(self, tenant_ref: TenantRef, *, display_name: str) -> Tenant: ...

    def ensure_client_redirect_uri(self, tenant_ref: TenantRef, *, redirect_uri: str) -> None: ...
